# GNU Make solution makefile autogenerated by Premake
# Type "make help" for usage help

ifndef config
  config=debug
endif
export config

PROJECTS := cparse cparsetest

.PHONY: all clean help $(PROJECTS)

all: $(PROJECTS)

cparse: 
	@echo "==== Building cparse ($(config)) ===="
	@${MAKE} --no-print-directory -C . -f cparse.make

cparsetest: cparse
	@echo "==== Building cparsetest ($(config)) ===="
	@${MAKE} --no-print-directory -C . -f cparsetest.make

clean:
	@${MAKE} --no-print-directory -C . -f cparse.make clean
	@${MAKE} --no-print-directory -C . -f cparsetest.make clean

help:
	@echo "Usage: make [config=name] [target]"
	@echo ""
	@echo "CONFIGURATIONS:"
	@echo "   debug"
	@echo "   release"
	@echo ""
	@echo "TARGETS:"
	@echo "   all (default)"
	@echo "   clean"
	@echo "   cparse"
	@echo "   cparsetest"
	@echo ""
	@echo "For more information, see http://industriousone.com/premake/quick-start"
